  File "main.py", line 18
SyntaxError: Non-ASCII character '\xc3' in file main.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
  File "main.py", line 18
SyntaxError: Non-ASCII character '\xc3' in file main.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from dateutil import parser
ImportError: No module named 'dateutil'
